# launch pdb on failure
pytest --pdb
